language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install autotools-dev automake autoconf libtool gperf xsltproc docbook-xsl
script: ./autogen.sh && ./configure && make V=1 distcheck
notifications:
  irc:
    channels:
      - "irc.freenode.org#gentoo-udev"
    on_success: change
    on_failure: always
